/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodiesApi);
  }
}(this, function(expect, FoodiesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FoodiesApi.ApiUsersMeGet200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiUsersMeGet200Response', function() {
    it('should create an instance of ApiUsersMeGet200Response', function() {
      // uncomment below and update the code to test ApiUsersMeGet200Response
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be.a(FoodiesApi.ApiUsersMeGet200Response);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property avatar (base name: "avatar")', function() {
      // uncomment below and update the code to test the property avatar
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property recipesCount (base name: "recipesCount")', function() {
      // uncomment below and update the code to test the property recipesCount
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property favoritesCount (base name: "favoritesCount")', function() {
      // uncomment below and update the code to test the property favoritesCount
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property followersCount (base name: "followersCount")', function() {
      // uncomment below and update the code to test the property followersCount
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property followingCount (base name: "followingCount")', function() {
      // uncomment below and update the code to test the property followingCount
      //var instance = new FoodiesApi.ApiUsersMeGet200Response();
      //expect(instance).to.be();
    });

  });

}));
