/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodiesApi);
  }
}(this, function(expect, FoodiesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiUsersUserIdFollowersGet200ResponseInnerUserFollow', function() {
    it('should create an instance of ApiUsersUserIdFollowersGet200ResponseInnerUserFollow', function() {
      // uncomment below and update the code to test ApiUsersUserIdFollowersGet200ResponseInnerUserFollow
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be.a(FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be();
    });

    it('should have the property followerId (base name: "followerId")', function() {
      // uncomment below and update the code to test the property followerId
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be();
    });

    it('should have the property followingId (base name: "followingId")', function() {
      // uncomment below and update the code to test the property followingId
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new FoodiesApi.ApiUsersUserIdFollowersGet200ResponseInnerUserFollow();
      //expect(instance).to.be();
    });

  });

}));
