/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodiesApi);
  }
}(this, function(expect, FoodiesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FoodiesApi.RecipePreview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecipePreview', function() {
    it('should create an instance of RecipePreview', function() {
      // uncomment below and update the code to test RecipePreview
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be.a(FoodiesApi.RecipePreview);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property userid (base name: "userid")', function() {
      // uncomment below and update the code to test the property userid
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property thumb (base name: "thumb")', function() {
      // uncomment below and update the code to test the property thumb
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property area (base name: "area")', function() {
      // uncomment below and update the code to test the property area
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property areaid (base name: "areaid")', function() {
      // uncomment below and update the code to test the property areaid
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property categoryid (base name: "categoryid")', function() {
      // uncomment below and update the code to test the property categoryid
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new FoodiesApi.RecipePreview();
      //expect(instance).to.be();
    });

  });

}));
