/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiCategoriesGet200ResponseInner model module.
 * @module model/ApiCategoriesGet200ResponseInner
 * @version 1.0.0
 */
class ApiCategoriesGet200ResponseInner {
    /**
     * Constructs a new <code>ApiCategoriesGet200ResponseInner</code>.
     * @alias module:model/ApiCategoriesGet200ResponseInner
     * @param id {String} Category unique identifier (ObjectId-like)
     * @param name {String} 
     */
    constructor(id, name) { 
        
        ApiCategoriesGet200ResponseInner.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ApiCategoriesGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiCategoriesGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiCategoriesGet200ResponseInner} The populated <code>ApiCategoriesGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiCategoriesGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiCategoriesGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiCategoriesGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiCategoriesGet200ResponseInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ApiCategoriesGet200ResponseInner.RequiredProperties = ["id", "name"];

/**
 * Category unique identifier (ObjectId-like)
 * @member {String} id
 */
ApiCategoriesGet200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiCategoriesGet200ResponseInner.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ApiCategoriesGet200ResponseInner.prototype['description'] = undefined;






export default ApiCategoriesGet200ResponseInner;

