/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiIngredientsGet200ResponseResultsInner model module.
 * @module model/ApiIngredientsGet200ResponseResultsInner
 * @version 1.0.0
 */
class ApiIngredientsGet200ResponseResultsInner {
    /**
     * Constructs a new <code>ApiIngredientsGet200ResponseResultsInner</code>.
     * @alias module:model/ApiIngredientsGet200ResponseResultsInner
     */
    constructor() { 
        
        ApiIngredientsGet200ResponseResultsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiIngredientsGet200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiIngredientsGet200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ApiIngredientsGet200ResponseResultsInner} The populated <code>ApiIngredientsGet200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiIngredientsGet200ResponseResultsInner();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('img')) {
                obj['img'] = ApiClient.convertToType(data['img'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiIngredientsGet200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiIngredientsGet200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['_id'] && !(typeof data['_id'] === 'string' || data['_id'] instanceof String)) {
            throw new Error("Expected the field `_id` to be a primitive type in the JSON string but got " + data['_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['desc'] && !(typeof data['desc'] === 'string' || data['desc'] instanceof String)) {
            throw new Error("Expected the field `desc` to be a primitive type in the JSON string but got " + data['desc']);
        }
        // ensure the json data is a string
        if (data['img'] && !(typeof data['img'] === 'string' || data['img'] instanceof String)) {
            throw new Error("Expected the field `img` to be a primitive type in the JSON string but got " + data['img']);
        }

        return true;
    }


}



/**
 * @member {String} _id
 */
ApiIngredientsGet200ResponseResultsInner.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
ApiIngredientsGet200ResponseResultsInner.prototype['name'] = undefined;

/**
 * @member {String} desc
 */
ApiIngredientsGet200ResponseResultsInner.prototype['desc'] = undefined;

/**
 * @member {String} img
 */
ApiIngredientsGet200ResponseResultsInner.prototype['img'] = undefined;






export default ApiIngredientsGet200ResponseResultsInner;

