/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiIngredientsGet200ResponseResultsInner from './ApiIngredientsGet200ResponseResultsInner';

/**
 * The ApiIngredientsGet200Response model module.
 * @module model/ApiIngredientsGet200Response
 * @version 1.0.0
 */
class ApiIngredientsGet200Response {
    /**
     * Constructs a new <code>ApiIngredientsGet200Response</code>.
     * @alias module:model/ApiIngredientsGet200Response
     */
    constructor() { 
        
        ApiIngredientsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiIngredientsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiIngredientsGet200Response} obj Optional instance to populate.
     * @return {module:model/ApiIngredientsGet200Response} The populated <code>ApiIngredientsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiIngredientsGet200Response();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [ApiIngredientsGet200ResponseResultsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiIngredientsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiIngredientsGet200Response</code>.
     */
    static validateJSON(data) {
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                ApiIngredientsGet200ResponseResultsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
ApiIngredientsGet200Response.prototype['total'] = undefined;

/**
 * @member {Number} page
 */
ApiIngredientsGet200Response.prototype['page'] = undefined;

/**
 * @member {Number} totalPages
 */
ApiIngredientsGet200Response.prototype['totalPages'] = undefined;

/**
 * @member {Array.<module:model/ApiIngredientsGet200ResponseResultsInner>} results
 */
ApiIngredientsGet200Response.prototype['results'] = undefined;






export default ApiIngredientsGet200Response;

