/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesGet200ResponseResultsInnerArea from './ApiRecipesGet200ResponseResultsInnerArea';
import ApiRecipesGet200ResponseResultsInnerCategory from './ApiRecipesGet200ResponseResultsInnerCategory';
import ApiRecipesGet200ResponseResultsInnerCreator from './ApiRecipesGet200ResponseResultsInnerCreator';

/**
 * The ApiRecipesGet200ResponseResultsInner model module.
 * @module model/ApiRecipesGet200ResponseResultsInner
 * @version 1.0.0
 */
class ApiRecipesGet200ResponseResultsInner {
    /**
     * Constructs a new <code>ApiRecipesGet200ResponseResultsInner</code>.
     * @alias module:model/ApiRecipesGet200ResponseResultsInner
     */
    constructor() { 
        
        ApiRecipesGet200ResponseResultsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiRecipesGet200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesGet200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesGet200ResponseResultsInner} The populated <code>ApiRecipesGet200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesGet200ResponseResultsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isFavorite')) {
                obj['isFavorite'] = ApiClient.convertToType(data['isFavorite'], 'Boolean');
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = ApiRecipesGet200ResponseResultsInnerCreator.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiRecipesGet200ResponseResultsInnerCategory.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiRecipesGet200ResponseResultsInnerArea.constructFromObject(data['area']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesGet200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesGet200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          ApiRecipesGet200ResponseResultsInnerCreator.validateJSON(data['Creator']);
        }
        // validate the optional field `category`
        if (data['category']) { // data not null
          ApiRecipesGet200ResponseResultsInnerCategory.validateJSON(data['category']);
        }
        // validate the optional field `area`
        if (data['area']) { // data not null
          ApiRecipesGet200ResponseResultsInnerArea.validateJSON(data['area']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiRecipesGet200ResponseResultsInner.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ApiRecipesGet200ResponseResultsInner.prototype['title'] = undefined;

/**
 * Cooking time in minutes
 * @member {Number} time
 */
ApiRecipesGet200ResponseResultsInner.prototype['time'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesGet200ResponseResultsInner.prototype['thumb'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesGet200ResponseResultsInner.prototype['description'] = undefined;

/**
 * Flag whether recipe is in the user's favorites. Appears only for authenticated users.
 * @member {Boolean} isFavorite
 */
ApiRecipesGet200ResponseResultsInner.prototype['isFavorite'] = undefined;

/**
 * @member {module:model/ApiRecipesGet200ResponseResultsInnerCreator} Creator
 */
ApiRecipesGet200ResponseResultsInner.prototype['Creator'] = undefined;

/**
 * @member {module:model/ApiRecipesGet200ResponseResultsInnerCategory} category
 */
ApiRecipesGet200ResponseResultsInner.prototype['category'] = undefined;

/**
 * @member {module:model/ApiRecipesGet200ResponseResultsInnerArea} area
 */
ApiRecipesGet200ResponseResultsInner.prototype['area'] = undefined;






export default ApiRecipesGet200ResponseResultsInner;

