/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesFavoritesGet200ResponseResultsInner model module.
 * @module model/ApiRecipesFavoritesGet200ResponseResultsInner
 * @version 1.0.0
 */
class ApiRecipesFavoritesGet200ResponseResultsInner {
    /**
     * Constructs a new <code>ApiRecipesFavoritesGet200ResponseResultsInner</code>.
     * @alias module:model/ApiRecipesFavoritesGet200ResponseResultsInner
     */
    constructor() { 
        
        ApiRecipesFavoritesGet200ResponseResultsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiRecipesFavoritesGet200ResponseResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesFavoritesGet200ResponseResultsInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesFavoritesGet200ResponseResultsInner} The populated <code>ApiRecipesFavoritesGet200ResponseResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesFavoritesGet200ResponseResultsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('categoryid')) {
                obj['categoryid'] = ApiClient.convertToType(data['categoryid'], 'String');
            }
            if (data.hasOwnProperty('areaid')) {
                obj['areaid'] = ApiClient.convertToType(data['areaid'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesFavoritesGet200ResponseResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesFavoritesGet200ResponseResultsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['categoryid'] && !(typeof data['categoryid'] === 'string' || data['categoryid'] instanceof String)) {
            throw new Error("Expected the field `categoryid` to be a primitive type in the JSON string but got " + data['categoryid']);
        }
        // ensure the json data is a string
        if (data['areaid'] && !(typeof data['areaid'] === 'string' || data['areaid'] instanceof String)) {
            throw new Error("Expected the field `areaid` to be a primitive type in the JSON string but got " + data['areaid']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['title'] = undefined;

/**
 * @member {String} categoryid
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['categoryid'] = undefined;

/**
 * @member {String} areaid
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['areaid'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['thumb'] = undefined;

/**
 * @member {Number} time
 */
ApiRecipesFavoritesGet200ResponseResultsInner.prototype['time'] = undefined;






export default ApiRecipesFavoritesGet200ResponseResultsInner;

