/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesPost201ResponseCreator model module.
 * @module model/ApiRecipesPost201ResponseCreator
 * @version 1.0.0
 */
class ApiRecipesPost201ResponseCreator {
    /**
     * Constructs a new <code>ApiRecipesPost201ResponseCreator</code>.
     * @alias module:model/ApiRecipesPost201ResponseCreator
     * @param id {String} 
     * @param username {String} 
     * @param avatar {String} 
     */
    constructor(id, username, avatar) { 
        
        ApiRecipesPost201ResponseCreator.initialize(this, id, username, avatar);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, avatar) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['avatar'] = avatar;
    }

    /**
     * Constructs a <code>ApiRecipesPost201ResponseCreator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPost201ResponseCreator} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPost201ResponseCreator} The populated <code>ApiRecipesPost201ResponseCreator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPost201ResponseCreator();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPost201ResponseCreator</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPost201ResponseCreator</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPost201ResponseCreator.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['avatar'] && !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)) {
            throw new Error("Expected the field `avatar` to be a primitive type in the JSON string but got " + data['avatar']);
        }

        return true;
    }


}

ApiRecipesPost201ResponseCreator.RequiredProperties = ["id", "username", "avatar"];

/**
 * @member {String} id
 */
ApiRecipesPost201ResponseCreator.prototype['id'] = undefined;

/**
 * @member {String} username
 */
ApiRecipesPost201ResponseCreator.prototype['username'] = undefined;

/**
 * @member {String} avatar
 */
ApiRecipesPost201ResponseCreator.prototype['avatar'] = undefined;






export default ApiRecipesPost201ResponseCreator;

