/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient from './ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient';

/**
 * The ApiRecipesPost201ResponseRecipeIngredientsInner model module.
 * @module model/ApiRecipesPost201ResponseRecipeIngredientsInner
 * @version 1.0.0
 */
class ApiRecipesPost201ResponseRecipeIngredientsInner {
    /**
     * Constructs a new <code>ApiRecipesPost201ResponseRecipeIngredientsInner</code>.
     * @alias module:model/ApiRecipesPost201ResponseRecipeIngredientsInner
     * @param measure {String} 
     * @param ingredient {module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient} 
     */
    constructor(measure, ingredient) { 
        
        ApiRecipesPost201ResponseRecipeIngredientsInner.initialize(this, measure, ingredient);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, measure, ingredient) { 
        obj['measure'] = measure;
        obj['ingredient'] = ingredient;
    }

    /**
     * Constructs a <code>ApiRecipesPost201ResponseRecipeIngredientsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPost201ResponseRecipeIngredientsInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPost201ResponseRecipeIngredientsInner} The populated <code>ApiRecipesPost201ResponseRecipeIngredientsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPost201ResponseRecipeIngredientsInner();

            if (data.hasOwnProperty('measure')) {
                obj['measure'] = ApiClient.convertToType(data['measure'], 'String');
            }
            if (data.hasOwnProperty('ingredient')) {
                obj['ingredient'] = ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.constructFromObject(data['ingredient']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPost201ResponseRecipeIngredientsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPost201ResponseRecipeIngredientsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPost201ResponseRecipeIngredientsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['measure'] && !(typeof data['measure'] === 'string' || data['measure'] instanceof String)) {
            throw new Error("Expected the field `measure` to be a primitive type in the JSON string but got " + data['measure']);
        }
        // validate the optional field `ingredient`
        if (data['ingredient']) { // data not null
          ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.validateJSON(data['ingredient']);
        }

        return true;
    }


}

ApiRecipesPost201ResponseRecipeIngredientsInner.RequiredProperties = ["measure", "ingredient"];

/**
 * @member {String} measure
 */
ApiRecipesPost201ResponseRecipeIngredientsInner.prototype['measure'] = undefined;

/**
 * @member {module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient} ingredient
 */
ApiRecipesPost201ResponseRecipeIngredientsInner.prototype['ingredient'] = undefined;






export default ApiRecipesPost201ResponseRecipeIngredientsInner;

