/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient from './ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient';

/**
 * The ApiRecipesIdGet200ResponseRecipeIngredientsInner model module.
 * @module model/ApiRecipesIdGet200ResponseRecipeIngredientsInner
 * @version 1.0.0
 */
class ApiRecipesIdGet200ResponseRecipeIngredientsInner {
    /**
     * Constructs a new <code>ApiRecipesIdGet200ResponseRecipeIngredientsInner</code>.
     * @alias module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInner
     */
    constructor() { 
        
        ApiRecipesIdGet200ResponseRecipeIngredientsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiRecipesIdGet200ResponseRecipeIngredientsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInner} The populated <code>ApiRecipesIdGet200ResponseRecipeIngredientsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesIdGet200ResponseRecipeIngredientsInner();

            if (data.hasOwnProperty('measure')) {
                obj['measure'] = ApiClient.convertToType(data['measure'], 'String');
            }
            if (data.hasOwnProperty('ingredient')) {
                obj['ingredient'] = ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient.constructFromObject(data['ingredient']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesIdGet200ResponseRecipeIngredientsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesIdGet200ResponseRecipeIngredientsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['measure'] && !(typeof data['measure'] === 'string' || data['measure'] instanceof String)) {
            throw new Error("Expected the field `measure` to be a primitive type in the JSON string but got " + data['measure']);
        }
        // validate the optional field `ingredient`
        if (data['ingredient']) { // data not null
          ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient.validateJSON(data['ingredient']);
        }

        return true;
    }


}



/**
 * @member {String} measure
 */
ApiRecipesIdGet200ResponseRecipeIngredientsInner.prototype['measure'] = undefined;

/**
 * @member {module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient} ingredient
 */
ApiRecipesIdGet200ResponseRecipeIngredientsInner.prototype['ingredient'] = undefined;






export default ApiRecipesIdGet200ResponseRecipeIngredientsInner;

