/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesGet200ResponseResultsInnerCreator from './ApiRecipesGet200ResponseResultsInnerCreator';

/**
 * The ApiRecipesPopularGet200ResponseInner model module.
 * @module model/ApiRecipesPopularGet200ResponseInner
 * @version 1.0.0
 */
class ApiRecipesPopularGet200ResponseInner {
    /**
     * Constructs a new <code>ApiRecipesPopularGet200ResponseInner</code>.
     * @alias module:model/ApiRecipesPopularGet200ResponseInner
     */
    constructor() { 
        
        ApiRecipesPopularGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiRecipesPopularGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPopularGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPopularGet200ResponseInner} The populated <code>ApiRecipesPopularGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPopularGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = ApiRecipesGet200ResponseResultsInnerCreator.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('favoritesCount')) {
                obj['favoritesCount'] = ApiClient.convertToType(data['favoritesCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPopularGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPopularGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          ApiRecipesGet200ResponseResultsInnerCreator.validateJSON(data['Creator']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiRecipesPopularGet200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ApiRecipesPopularGet200ResponseInner.prototype['title'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesPopularGet200ResponseInner.prototype['thumb'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesPopularGet200ResponseInner.prototype['description'] = undefined;

/**
 * @member {module:model/ApiRecipesGet200ResponseResultsInnerCreator} Creator
 */
ApiRecipesPopularGet200ResponseInner.prototype['Creator'] = undefined;

/**
 * @member {Number} favoritesCount
 */
ApiRecipesPopularGet200ResponseInner.prototype['favoritesCount'] = undefined;






export default ApiRecipesPopularGet200ResponseInner;

