/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient model module.
 * @module model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient
 * @version 1.0.0
 */
class ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient {
    /**
     * Constructs a new <code>ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient</code>.
     * @alias module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient
     * @param id {String} 
     * @param name {String} 
     * @param img {String} 
     * @param description {String} 
     */
    constructor(id, name, img, description) { 
        
        ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.initialize(this, id, name, img, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, img, description) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['img'] = img;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient} The populated <code>ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('img')) {
                obj['img'] = ApiClient.convertToType(data['img'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['img'] && !(typeof data['img'] === 'string' || data['img'] instanceof String)) {
            throw new Error("Expected the field `img` to be a primitive type in the JSON string but got " + data['img']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.RequiredProperties = ["id", "name", "img", "description"];

/**
 * @member {String} id
 */
ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.prototype['name'] = undefined;

/**
 * @member {String} img
 */
ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.prototype['img'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient.prototype['description'] = undefined;






export default ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient;

