/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesIdGet200ResponseRecipeIngredientsInner from './ApiRecipesIdGet200ResponseRecipeIngredientsInner';

/**
 * The ApiRecipesIdGet200Response model module.
 * @module model/ApiRecipesIdGet200Response
 * @version 1.0.0
 */
class ApiRecipesIdGet200Response {
    /**
     * Constructs a new <code>ApiRecipesIdGet200Response</code>.
     * @alias module:model/ApiRecipesIdGet200Response
     */
    constructor() { 
        
        ApiRecipesIdGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiRecipesIdGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesIdGet200Response} obj Optional instance to populate.
     * @return {module:model/ApiRecipesIdGet200Response} The populated <code>ApiRecipesIdGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesIdGet200Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('categoryid')) {
                obj['categoryid'] = ApiClient.convertToType(data['categoryid'], 'String');
            }
            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('areaid')) {
                obj['areaid'] = ApiClient.convertToType(data['areaid'], 'String');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('recipeIngredients')) {
                obj['recipeIngredients'] = ApiClient.convertToType(data['recipeIngredients'], [ApiRecipesIdGet200ResponseRecipeIngredientsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesIdGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesIdGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['categoryid'] && !(typeof data['categoryid'] === 'string' || data['categoryid'] instanceof String)) {
            throw new Error("Expected the field `categoryid` to be a primitive type in the JSON string but got " + data['categoryid']);
        }
        // ensure the json data is a string
        if (data['userid'] && !(typeof data['userid'] === 'string' || data['userid'] instanceof String)) {
            throw new Error("Expected the field `userid` to be a primitive type in the JSON string but got " + data['userid']);
        }
        // ensure the json data is a string
        if (data['areaid'] && !(typeof data['areaid'] === 'string' || data['areaid'] instanceof String)) {
            throw new Error("Expected the field `areaid` to be a primitive type in the JSON string but got " + data['areaid']);
        }
        // ensure the json data is a string
        if (data['instructions'] && !(typeof data['instructions'] === 'string' || data['instructions'] instanceof String)) {
            throw new Error("Expected the field `instructions` to be a primitive type in the JSON string but got " + data['instructions']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        if (data['recipeIngredients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recipeIngredients'])) {
                throw new Error("Expected the field `recipeIngredients` to be an array in the JSON data but got " + data['recipeIngredients']);
            }
            // validate the optional field `recipeIngredients` (array)
            for (const item of data['recipeIngredients']) {
                ApiRecipesIdGet200ResponseRecipeIngredientsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiRecipesIdGet200Response.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ApiRecipesIdGet200Response.prototype['title'] = undefined;

/**
 * @member {String} categoryid
 */
ApiRecipesIdGet200Response.prototype['categoryid'] = undefined;

/**
 * @member {String} userid
 */
ApiRecipesIdGet200Response.prototype['userid'] = undefined;

/**
 * @member {String} areaid
 */
ApiRecipesIdGet200Response.prototype['areaid'] = undefined;

/**
 * @member {String} instructions
 */
ApiRecipesIdGet200Response.prototype['instructions'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesIdGet200Response.prototype['description'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesIdGet200Response.prototype['thumb'] = undefined;

/**
 * @member {Number} time
 */
ApiRecipesIdGet200Response.prototype['time'] = undefined;

/**
 * @member {Array.<module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInner>} recipeIngredients
 */
ApiRecipesIdGet200Response.prototype['recipeIngredients'] = undefined;






export default ApiRecipesIdGet200Response;

