/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesIdGet200ResponseArea model module.
 * @module model/ApiRecipesIdGet200ResponseArea
 * @version 1.0.0
 */
class ApiRecipesIdGet200ResponseArea {
  /**
   * Constructs a new <code>ApiRecipesIdGet200ResponseArea</code>.
   * @alias module:model/ApiRecipesIdGet200ResponseArea
   */
  constructor() {
    ApiRecipesIdGet200ResponseArea.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ApiRecipesIdGet200ResponseArea</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiRecipesIdGet200ResponseArea} obj Optional instance to populate.
   * @return {module:model/ApiRecipesIdGet200ResponseArea} The populated <code>ApiRecipesIdGet200ResponseArea</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiRecipesIdGet200ResponseArea();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ApiRecipesIdGet200ResponseArea</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesIdGet200ResponseArea</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data['id'] &&
      !(typeof data['id'] === 'string' || data['id'] instanceof String)
    ) {
      throw new Error(
        'Expected the field `id` to be a primitive type in the JSON string but got ' +
          data['id']
      );
    }
    // ensure the json data is a string
    if (
      data['name'] &&
      !(typeof data['name'] === 'string' || data['name'] instanceof String)
    ) {
      throw new Error(
        'Expected the field `name` to be a primitive type in the JSON string but got ' +
          data['name']
      );
    }

    return true;
  }
}

/**
 * @member {String} id
 */
ApiRecipesIdGet200ResponseArea.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiRecipesIdGet200ResponseArea.prototype['name'] = undefined;

export default ApiRecipesIdGet200ResponseArea;
