/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesPost201ResponseArea from './ApiRecipesPost201ResponseArea';
import ApiRecipesPost201ResponseCategory from './ApiRecipesPost201ResponseCategory';
import ApiRecipesPost201ResponseCreator from './ApiRecipesPost201ResponseCreator';
import ApiRecipesPost201ResponseRecipeIngredientsInner from './ApiRecipesPost201ResponseRecipeIngredientsInner';

/**
 * The ApiRecipesPost201Response model module.
 * @module model/ApiRecipesPost201Response
 * @version 1.0.0
 */
class ApiRecipesPost201Response {
    /**
     * Constructs a new <code>ApiRecipesPost201Response</code>.
     * @alias module:model/ApiRecipesPost201Response
     * @param id {String} 
     * @param title {String} 
     * @param time {Number} 
     * @param description {String} 
     * @param instructions {String} 
     * @param thumb {String} 
     * @param isFavorite {Boolean} 
     * @param creator {module:model/ApiRecipesPost201ResponseCreator} 
     * @param category {module:model/ApiRecipesPost201ResponseCategory} 
     * @param area {module:model/ApiRecipesPost201ResponseArea} 
     * @param recipeIngredients {Array.<module:model/ApiRecipesPost201ResponseRecipeIngredientsInner>} 
     */
    constructor(id, title, time, description, instructions, thumb, isFavorite, creator, category, area, recipeIngredients) { 
        
        ApiRecipesPost201Response.initialize(this, id, title, time, description, instructions, thumb, isFavorite, creator, category, area, recipeIngredients);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, time, description, instructions, thumb, isFavorite, creator, category, area, recipeIngredients) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['time'] = time;
        obj['description'] = description;
        obj['instructions'] = instructions;
        obj['thumb'] = thumb;
        obj['isFavorite'] = isFavorite;
        obj['Creator'] = creator;
        obj['category'] = category;
        obj['area'] = area;
        obj['recipeIngredients'] = recipeIngredients;
    }

    /**
     * Constructs a <code>ApiRecipesPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPost201Response} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPost201Response} The populated <code>ApiRecipesPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPost201Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('isFavorite')) {
                obj['isFavorite'] = ApiClient.convertToType(data['isFavorite'], 'Boolean');
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = ApiRecipesPost201ResponseCreator.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiRecipesPost201ResponseCategory.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiRecipesPost201ResponseArea.constructFromObject(data['area']);
            }
            if (data.hasOwnProperty('recipeIngredients')) {
                obj['recipeIngredients'] = ApiClient.convertToType(data['recipeIngredients'], [ApiRecipesPost201ResponseRecipeIngredientsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPost201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPost201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['instructions'] && !(typeof data['instructions'] === 'string' || data['instructions'] instanceof String)) {
            throw new Error("Expected the field `instructions` to be a primitive type in the JSON string but got " + data['instructions']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          ApiRecipesPost201ResponseCreator.validateJSON(data['Creator']);
        }
        // validate the optional field `category`
        if (data['category']) { // data not null
          ApiRecipesPost201ResponseCategory.validateJSON(data['category']);
        }
        // validate the optional field `area`
        if (data['area']) { // data not null
          ApiRecipesPost201ResponseArea.validateJSON(data['area']);
        }
        if (data['recipeIngredients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recipeIngredients'])) {
                throw new Error("Expected the field `recipeIngredients` to be an array in the JSON data but got " + data['recipeIngredients']);
            }
            // validate the optional field `recipeIngredients` (array)
            for (const item of data['recipeIngredients']) {
                ApiRecipesPost201ResponseRecipeIngredientsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiRecipesPost201Response.RequiredProperties = ["id", "title", "time", "description", "instructions", "thumb", "isFavorite", "Creator", "category", "area", "recipeIngredients"];

/**
 * @member {String} id
 */
ApiRecipesPost201Response.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ApiRecipesPost201Response.prototype['title'] = undefined;

/**
 * @member {Number} time
 */
ApiRecipesPost201Response.prototype['time'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesPost201Response.prototype['description'] = undefined;

/**
 * @member {String} instructions
 */
ApiRecipesPost201Response.prototype['instructions'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesPost201Response.prototype['thumb'] = undefined;

/**
 * @member {Boolean} isFavorite
 */
ApiRecipesPost201Response.prototype['isFavorite'] = undefined;

/**
 * @member {module:model/ApiRecipesPost201ResponseCreator} Creator
 */
ApiRecipesPost201Response.prototype['Creator'] = undefined;

/**
 * @member {module:model/ApiRecipesPost201ResponseCategory} category
 */
ApiRecipesPost201Response.prototype['category'] = undefined;

/**
 * @member {module:model/ApiRecipesPost201ResponseArea} area
 */
ApiRecipesPost201Response.prototype['area'] = undefined;

/**
 * @member {Array.<module:model/ApiRecipesPost201ResponseRecipeIngredientsInner>} recipeIngredients
 */
ApiRecipesPost201Response.prototype['recipeIngredients'] = undefined;






export default ApiRecipesPost201Response;

