/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesGet200ResponseResultsInnerCreator model module.
 * @module model/ApiRecipesGet200ResponseResultsInnerCreator
 * @version 1.0.0
 */
class ApiRecipesGet200ResponseResultsInnerCreator {
  /**
   * Constructs a new <code>ApiRecipesGet200ResponseResultsInnerCreator</code>.
   * @alias module:model/ApiRecipesGet200ResponseResultsInnerCreator
   */
  constructor() {
    ApiRecipesGet200ResponseResultsInnerCreator.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ApiRecipesGet200ResponseResultsInnerCreator</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiRecipesGet200ResponseResultsInnerCreator} obj Optional instance to populate.
   * @return {module:model/ApiRecipesGet200ResponseResultsInnerCreator} The populated <code>ApiRecipesGet200ResponseResultsInnerCreator</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiRecipesGet200ResponseResultsInnerCreator();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('avatar')) {
        obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ApiRecipesGet200ResponseResultsInnerCreator</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesGet200ResponseResultsInnerCreator</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data['id'] &&
      !(typeof data['id'] === 'string' || data['id'] instanceof String)
    ) {
      throw new Error(
        'Expected the field `id` to be a primitive type in the JSON string but got ' +
          data['id']
      );
    }
    // ensure the json data is a string
    if (
      data['username'] &&
      !(
        typeof data['username'] === 'string' ||
        data['username'] instanceof String
      )
    ) {
      throw new Error(
        'Expected the field `username` to be a primitive type in the JSON string but got ' +
          data['username']
      );
    }
    // ensure the json data is a string
    if (
      data['avatar'] &&
      !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)
    ) {
      throw new Error(
        'Expected the field `avatar` to be a primitive type in the JSON string but got ' +
          data['avatar']
      );
    }

    return true;
  }
}

/**
 * @member {String} id
 */
ApiRecipesGet200ResponseResultsInnerCreator.prototype['id'] = undefined;

/**
 * @member {String} username
 */
ApiRecipesGet200ResponseResultsInnerCreator.prototype['username'] = undefined;

/**
 * @member {String} avatar
 */
ApiRecipesGet200ResponseResultsInnerCreator.prototype['avatar'] = undefined;

export default ApiRecipesGet200ResponseResultsInnerCreator;
