/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesPostRequestIngredientsInner from './ApiRecipesPostRequestIngredientsInner';

/**
 * The ApiRecipesPostRequest model module.
 * @module model/ApiRecipesPostRequest
 * @version 1.0.0
 */
class ApiRecipesPostRequest {
    /**
     * Constructs a new <code>ApiRecipesPostRequest</code>.
     * @alias module:model/ApiRecipesPostRequest
     * @param title {String} 
     * @param categoryid {String} 
     * @param instructions {String} 
     * @param time {Number} 
     * @param ingredients {Array.<module:model/ApiRecipesPostRequestIngredientsInner>} 
     */
    constructor(title, categoryid, instructions, time, ingredients) { 
        
        ApiRecipesPostRequest.initialize(this, title, categoryid, instructions, time, ingredients);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, categoryid, instructions, time, ingredients) { 
        obj['title'] = title;
        obj['categoryid'] = categoryid;
        obj['instructions'] = instructions;
        obj['time'] = time;
        obj['ingredients'] = ingredients;
    }

    /**
     * Constructs a <code>ApiRecipesPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPostRequest} The populated <code>ApiRecipesPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPostRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('categoryid')) {
                obj['categoryid'] = ApiClient.convertToType(data['categoryid'], 'String');
            }
            if (data.hasOwnProperty('areaid')) {
                obj['areaid'] = ApiClient.convertToType(data['areaid'], 'String');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('ingredients')) {
                obj['ingredients'] = ApiClient.convertToType(data['ingredients'], [ApiRecipesPostRequestIngredientsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['categoryid'] && !(typeof data['categoryid'] === 'string' || data['categoryid'] instanceof String)) {
            throw new Error("Expected the field `categoryid` to be a primitive type in the JSON string but got " + data['categoryid']);
        }
        // ensure the json data is a string
        if (data['areaid'] && !(typeof data['areaid'] === 'string' || data['areaid'] instanceof String)) {
            throw new Error("Expected the field `areaid` to be a primitive type in the JSON string but got " + data['areaid']);
        }
        // ensure the json data is a string
        if (data['instructions'] && !(typeof data['instructions'] === 'string' || data['instructions'] instanceof String)) {
            throw new Error("Expected the field `instructions` to be a primitive type in the JSON string but got " + data['instructions']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        if (data['ingredients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ingredients'])) {
                throw new Error("Expected the field `ingredients` to be an array in the JSON data but got " + data['ingredients']);
            }
            // validate the optional field `ingredients` (array)
            for (const item of data['ingredients']) {
                ApiRecipesPostRequestIngredientsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiRecipesPostRequest.RequiredProperties = ["title", "categoryid", "instructions", "time", "ingredients"];

/**
 * @member {String} title
 */
ApiRecipesPostRequest.prototype['title'] = undefined;

/**
 * @member {String} categoryid
 */
ApiRecipesPostRequest.prototype['categoryid'] = undefined;

/**
 * @member {String} areaid
 */
ApiRecipesPostRequest.prototype['areaid'] = undefined;

/**
 * @member {String} instructions
 */
ApiRecipesPostRequest.prototype['instructions'] = undefined;

/**
 * @member {String} description
 */
ApiRecipesPostRequest.prototype['description'] = undefined;

/**
 * @member {String} thumb
 */
ApiRecipesPostRequest.prototype['thumb'] = undefined;

/**
 * @member {Number} time
 */
ApiRecipesPostRequest.prototype['time'] = undefined;

/**
 * @member {Array.<module:model/ApiRecipesPostRequestIngredientsInner>} ingredients
 */
ApiRecipesPostRequest.prototype['ingredients'] = undefined;






export default ApiRecipesPostRequest;

