/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRecipesPostRequestIngredientsInner model module.
 * @module model/ApiRecipesPostRequestIngredientsInner
 * @version 1.0.0
 */
class ApiRecipesPostRequestIngredientsInner {
    /**
     * Constructs a new <code>ApiRecipesPostRequestIngredientsInner</code>.
     * @alias module:model/ApiRecipesPostRequestIngredientsInner
     * @param id {String} 
     */
    constructor(id) { 
        
        ApiRecipesPostRequestIngredientsInner.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>ApiRecipesPostRequestIngredientsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRecipesPostRequestIngredientsInner} obj Optional instance to populate.
     * @return {module:model/ApiRecipesPostRequestIngredientsInner} The populated <code>ApiRecipesPostRequestIngredientsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRecipesPostRequestIngredientsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('measure')) {
                obj['measure'] = ApiClient.convertToType(data['measure'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRecipesPostRequestIngredientsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRecipesPostRequestIngredientsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRecipesPostRequestIngredientsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['measure'] && !(typeof data['measure'] === 'string' || data['measure'] instanceof String)) {
            throw new Error("Expected the field `measure` to be a primitive type in the JSON string but got " + data['measure']);
        }

        return true;
    }


}

ApiRecipesPostRequestIngredientsInner.RequiredProperties = ["id"];

/**
 * @member {String} id
 */
ApiRecipesPostRequestIngredientsInner.prototype['id'] = undefined;

/**
 * @member {String} measure
 */
ApiRecipesPostRequestIngredientsInner.prototype['measure'] = undefined;






export default ApiRecipesPostRequestIngredientsInner;

