/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTestimonialsGet200ResponseInnerUser from './ApiTestimonialsGet200ResponseInnerUser';

/**
 * The ApiTestimonialsGet200ResponseInner model module.
 * @module model/ApiTestimonialsGet200ResponseInner
 * @version 1.0.0
 */
class ApiTestimonialsGet200ResponseInner {
    /**
     * Constructs a new <code>ApiTestimonialsGet200ResponseInner</code>.
     * @alias module:model/ApiTestimonialsGet200ResponseInner
     */
    constructor() { 
        
        ApiTestimonialsGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiTestimonialsGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTestimonialsGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiTestimonialsGet200ResponseInner} The populated <code>ApiTestimonialsGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTestimonialsGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiTestimonialsGet200ResponseInnerUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTestimonialsGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTestimonialsGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['userid'] && !(typeof data['userid'] === 'string' || data['userid'] instanceof String)) {
            throw new Error("Expected the field `userid` to be a primitive type in the JSON string but got " + data['userid']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          ApiTestimonialsGet200ResponseInnerUser.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiTestimonialsGet200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} userid
 */
ApiTestimonialsGet200ResponseInner.prototype['userid'] = undefined;

/**
 * @member {String} text
 */
ApiTestimonialsGet200ResponseInner.prototype['text'] = undefined;

/**
 * @member {Date} createdAt
 */
ApiTestimonialsGet200ResponseInner.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ApiTestimonialsGet200ResponseInner.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/ApiTestimonialsGet200ResponseInnerUser} user
 */
ApiTestimonialsGet200ResponseInner.prototype['user'] = undefined;






export default ApiTestimonialsGet200ResponseInner;

