/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiUsersUserIdGet200Response model module.
 * @module model/ApiUsersUserIdGet200Response
 * @version 1.0.0
 */
class ApiUsersUserIdGet200Response {
    /**
     * Constructs a new <code>ApiUsersUserIdGet200Response</code>.
     * @alias module:model/ApiUsersUserIdGet200Response
     */
    constructor() { 
        
        ApiUsersUserIdGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiUsersUserIdGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUsersUserIdGet200Response} obj Optional instance to populate.
     * @return {module:model/ApiUsersUserIdGet200Response} The populated <code>ApiUsersUserIdGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUsersUserIdGet200Response();

            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('recipesCount')) {
                obj['recipesCount'] = ApiClient.convertToType(data['recipesCount'], 'Number');
            }
            if (data.hasOwnProperty('followersCount')) {
                obj['followersCount'] = ApiClient.convertToType(data['followersCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiUsersUserIdGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUsersUserIdGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['avatar'] && !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)) {
            throw new Error("Expected the field `avatar` to be a primitive type in the JSON string but got " + data['avatar']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}



/**
 * @member {String} avatar
 */
ApiUsersUserIdGet200Response.prototype['avatar'] = undefined;

/**
 * @member {String} name
 */
ApiUsersUserIdGet200Response.prototype['name'] = undefined;

/**
 * @member {String} email
 */
ApiUsersUserIdGet200Response.prototype['email'] = undefined;

/**
 * @member {Number} recipesCount
 */
ApiUsersUserIdGet200Response.prototype['recipesCount'] = undefined;

/**
 * @member {Number} followersCount
 */
ApiUsersUserIdGet200Response.prototype['followersCount'] = undefined;






export default ApiUsersUserIdGet200Response;

