/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiUsersUserIdFollowersGet200ResponseInnerUserFollow from './ApiUsersUserIdFollowersGet200ResponseInnerUserFollow';

/**
 * The ApiUsersUserIdFollowersGet200ResponseInner model module.
 * @module model/ApiUsersUserIdFollowersGet200ResponseInner
 * @version 1.0.0
 */
class ApiUsersUserIdFollowersGet200ResponseInner {
    /**
     * Constructs a new <code>ApiUsersUserIdFollowersGet200ResponseInner</code>.
     * @alias module:model/ApiUsersUserIdFollowersGet200ResponseInner
     */
    constructor() { 
        
        ApiUsersUserIdFollowersGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiUsersUserIdFollowersGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUsersUserIdFollowersGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ApiUsersUserIdFollowersGet200ResponseInner} The populated <code>ApiUsersUserIdFollowersGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUsersUserIdFollowersGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('totalRecipes')) {
                obj['totalRecipes'] = ApiClient.convertToType(data['totalRecipes'], 'Number');
            }
            if (data.hasOwnProperty('user_follow')) {
                obj['user_follow'] = ApiUsersUserIdFollowersGet200ResponseInnerUserFollow.constructFromObject(data['user_follow']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiUsersUserIdFollowersGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUsersUserIdFollowersGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['avatar'] && !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)) {
            throw new Error("Expected the field `avatar` to be a primitive type in the JSON string but got " + data['avatar']);
        }
        // validate the optional field `user_follow`
        if (data['user_follow']) { // data not null
          ApiUsersUserIdFollowersGet200ResponseInnerUserFollow.validateJSON(data['user_follow']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} email
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['email'] = undefined;

/**
 * @member {String} username
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['username'] = undefined;

/**
 * @member {String} avatar
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['avatar'] = undefined;

/**
 * @member {Number} totalRecipes
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['totalRecipes'] = undefined;

/**
 * @member {module:model/ApiUsersUserIdFollowersGet200ResponseInnerUserFollow} user_follow
 */
ApiUsersUserIdFollowersGet200ResponseInner.prototype['user_follow'] = undefined;






export default ApiUsersUserIdFollowersGet200ResponseInner;

