/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiUsersFollowingGet200ResponseInnerUserFollow model module.
 * @module model/ApiUsersFollowingGet200ResponseInnerUserFollow
 * @version 1.0.0
 */
class ApiUsersFollowingGet200ResponseInnerUserFollow {
    /**
     * Constructs a new <code>ApiUsersFollowingGet200ResponseInnerUserFollow</code>.
     * @alias module:model/ApiUsersFollowingGet200ResponseInnerUserFollow
     */
    constructor() { 
        
        ApiUsersFollowingGet200ResponseInnerUserFollow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiUsersFollowingGet200ResponseInnerUserFollow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUsersFollowingGet200ResponseInnerUserFollow} obj Optional instance to populate.
     * @return {module:model/ApiUsersFollowingGet200ResponseInnerUserFollow} The populated <code>ApiUsersFollowingGet200ResponseInnerUserFollow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUsersFollowingGet200ResponseInnerUserFollow();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('followerId')) {
                obj['followerId'] = ApiClient.convertToType(data['followerId'], 'String');
            }
            if (data.hasOwnProperty('followingId')) {
                obj['followingId'] = ApiClient.convertToType(data['followingId'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiUsersFollowingGet200ResponseInnerUserFollow</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUsersFollowingGet200ResponseInnerUserFollow</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['followerId'] && !(typeof data['followerId'] === 'string' || data['followerId'] instanceof String)) {
            throw new Error("Expected the field `followerId` to be a primitive type in the JSON string but got " + data['followerId']);
        }
        // ensure the json data is a string
        if (data['followingId'] && !(typeof data['followingId'] === 'string' || data['followingId'] instanceof String)) {
            throw new Error("Expected the field `followingId` to be a primitive type in the JSON string but got " + data['followingId']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ApiUsersFollowingGet200ResponseInnerUserFollow.prototype['id'] = undefined;

/**
 * @member {String} followerId
 */
ApiUsersFollowingGet200ResponseInnerUserFollow.prototype['followerId'] = undefined;

/**
 * @member {String} followingId
 */
ApiUsersFollowingGet200ResponseInnerUserFollow.prototype['followingId'] = undefined;

/**
 * @member {Date} createdAt
 */
ApiUsersFollowingGet200ResponseInnerUserFollow.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ApiUsersFollowingGet200ResponseInnerUserFollow.prototype['updatedAt'] = undefined;






export default ApiUsersFollowingGet200ResponseInnerUserFollow;

