/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesFavoritesGet200ResponseResultsInner from './ApiRecipesFavoritesGet200ResponseResultsInner';

/**
 * The ApiUsersRecipesGet200Response model module.
 * @module model/ApiUsersRecipesGet200Response
 * @version 1.0.0
 */
class ApiUsersRecipesGet200Response {
  /**
   * Constructs a new <code>ApiUsersRecipesGet200Response</code>.
   * @alias module:model/ApiUsersRecipesGet200Response
   */
  constructor() {
    ApiUsersRecipesGet200Response.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>ApiUsersRecipesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiUsersRecipesGet200Response} obj Optional instance to populate.
   * @return {module:model/ApiUsersRecipesGet200Response} The populated <code>ApiUsersRecipesGet200Response</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiUsersRecipesGet200Response();

      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('page')) {
        obj['page'] = ApiClient.convertToType(data['page'], 'Number');
      }
      if (data.hasOwnProperty('totalPages')) {
        obj['totalPages'] = ApiClient.convertToType(
          data['totalPages'],
          'Number'
        );
      }

      if (data.hasOwnProperty('recipes')) {
        obj['recipes'] = ApiClient.convertToType(data['recipes'], [
          ApiRecipesFavoritesGet200ResponseResultsInner,
        ]);
        obj['results'] = obj['recipes'];
      } else if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [
          ApiRecipesFavoritesGet200ResponseResultsInner,
        ]);
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>ApiUsersRecipesGet200Response</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUsersRecipesGet200Response</code>.
   */
  static validateJSON(data) {
    if (data['results']) {
      // data not null
      // ensure the json data is an array
      if (!Array.isArray(data['results'])) {
        throw new Error(
          'Expected the field `results` to be an array in the JSON data but got ' +
            data['results']
        );
      }
      // validate the optional field `results` (array)
      for (const item of data['results']) {
        ApiRecipesFavoritesGet200ResponseResultsInner.validateJSON(item);
      }
    }

    return true;
  }
}

/**
 * @member {Number} total
 */
ApiUsersRecipesGet200Response.prototype['total'] = undefined;

/**
 * @member {Number} page
 */
ApiUsersRecipesGet200Response.prototype['page'] = undefined;

/**
 * @member {Number} totalPages
 */
ApiUsersRecipesGet200Response.prototype['totalPages'] = undefined;

/**
 * @member {Array.<module:model/ApiRecipesFavoritesGet200ResponseResultsInner>} results
 */
ApiUsersRecipesGet200Response.prototype['results'] = undefined;

export default ApiUsersRecipesGet200Response;
