/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesPopularGet200ResponseInnerCreator from './ApiRecipesPopularGet200ResponseInnerCreator';

/**
 * The PopularRecipe model module.
 * @module model/PopularRecipe
 * @version 1.0.0
 */
class PopularRecipe {
    /**
     * Constructs a new <code>PopularRecipe</code>.
     * @alias module:model/PopularRecipe
     */
    constructor() { 
        
        PopularRecipe.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PopularRecipe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PopularRecipe} obj Optional instance to populate.
     * @return {module:model/PopularRecipe} The populated <code>PopularRecipe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PopularRecipe();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isFavorite')) {
                obj['isFavorite'] = ApiClient.convertToType(data['isFavorite'], 'Boolean');
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = ApiRecipesPopularGet200ResponseInnerCreator.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('favoritesCount')) {
                obj['favoritesCount'] = ApiClient.convertToType(data['favoritesCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PopularRecipe</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PopularRecipe</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          ApiRecipesPopularGet200ResponseInnerCreator.validateJSON(data['Creator']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PopularRecipe.prototype['id'] = undefined;

/**
 * @member {String} title
 */
PopularRecipe.prototype['title'] = undefined;

/**
 * @member {String} thumb
 */
PopularRecipe.prototype['thumb'] = undefined;

/**
 * @member {String} description
 */
PopularRecipe.prototype['description'] = undefined;

/**
 * Flag whether recipe is in the user's favorites. Appears only for authenticated users.
 * @member {Boolean} isFavorite
 */
PopularRecipe.prototype['isFavorite'] = undefined;

/**
 * @member {module:model/ApiRecipesPopularGet200ResponseInnerCreator} Creator
 */
PopularRecipe.prototype['Creator'] = undefined;

/**
 * @member {Number} favoritesCount
 */
PopularRecipe.prototype['favoritesCount'] = undefined;






export default PopularRecipe;

