/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRecipesIdGet200ResponseArea from './ApiRecipesIdGet200ResponseArea';
import ApiRecipesIdGet200ResponseCategory from './ApiRecipesIdGet200ResponseCategory';
import ApiRecipesIdGet200ResponseCreator from './ApiRecipesIdGet200ResponseCreator';
import RecipeIngredientItem from './RecipeIngredientItem';

/**
 * The Recipe model module.
 * @module model/Recipe
 * @version 1.0.0
 */
class Recipe {
    /**
     * Constructs a new <code>Recipe</code>.
     * @alias module:model/Recipe
     */
    constructor() { 
        
        Recipe.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Recipe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Recipe} obj Optional instance to populate.
     * @return {module:model/Recipe} The populated <code>Recipe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Recipe();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('Creator')) {
                obj['Creator'] = ApiRecipesIdGet200ResponseCreator.constructFromObject(data['Creator']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiRecipesIdGet200ResponseCategory.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiRecipesIdGet200ResponseArea.constructFromObject(data['area']);
            }
            if (data.hasOwnProperty('recipeIngredients')) {
                obj['recipeIngredients'] = ApiClient.convertToType(data['recipeIngredients'], [RecipeIngredientItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Recipe</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Recipe</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['instructions'] && !(typeof data['instructions'] === 'string' || data['instructions'] instanceof String)) {
            throw new Error("Expected the field `instructions` to be a primitive type in the JSON string but got " + data['instructions']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // validate the optional field `Creator`
        if (data['Creator']) { // data not null
          ApiRecipesIdGet200ResponseCreator.validateJSON(data['Creator']);
        }
        // validate the optional field `category`
        if (data['category']) { // data not null
          ApiRecipesIdGet200ResponseCategory.validateJSON(data['category']);
        }
        // validate the optional field `area`
        if (data['area']) { // data not null
          ApiRecipesIdGet200ResponseArea.validateJSON(data['area']);
        }
        if (data['recipeIngredients']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['recipeIngredients'])) {
                throw new Error("Expected the field `recipeIngredients` to be an array in the JSON data but got " + data['recipeIngredients']);
            }
            // validate the optional field `recipeIngredients` (array)
            for (const item of data['recipeIngredients']) {
                RecipeIngredientItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Recipe.prototype['id'] = undefined;

/**
 * @member {String} title
 */
Recipe.prototype['title'] = undefined;

/**
 * Cooking time in minutes
 * @member {Number} time
 */
Recipe.prototype['time'] = undefined;

/**
 * @member {String} description
 */
Recipe.prototype['description'] = undefined;

/**
 * @member {String} instructions
 */
Recipe.prototype['instructions'] = undefined;

/**
 * @member {String} thumb
 */
Recipe.prototype['thumb'] = undefined;

/**
 * @member {module:model/ApiRecipesIdGet200ResponseCreator} Creator
 */
Recipe.prototype['Creator'] = undefined;

/**
 * @member {module:model/ApiRecipesIdGet200ResponseCategory} category
 */
Recipe.prototype['category'] = undefined;

/**
 * @member {module:model/ApiRecipesIdGet200ResponseArea} area
 */
Recipe.prototype['area'] = undefined;

/**
 * @member {Array.<module:model/RecipeIngredientItem>} recipeIngredients
 */
Recipe.prototype['recipeIngredients'] = undefined;






export default Recipe;

