/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecipePreview model module.
 * @module model/RecipePreview
 * @version 1.0.0
 */
class RecipePreview {
    /**
     * Constructs a new <code>RecipePreview</code>.
     * @alias module:model/RecipePreview
     */
    constructor() { 
        
        RecipePreview.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecipePreview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecipePreview} obj Optional instance to populate.
     * @return {module:model/RecipePreview} The populated <code>RecipePreview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipePreview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userid')) {
                obj['userid'] = ApiClient.convertToType(data['userid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('area')) {
                obj['area'] = ApiClient.convertToType(data['area'], 'String');
            }
            if (data.hasOwnProperty('areaid')) {
                obj['areaid'] = ApiClient.convertToType(data['areaid'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('categoryid')) {
                obj['categoryid'] = ApiClient.convertToType(data['categoryid'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecipePreview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecipePreview</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['userid'] && !(typeof data['userid'] === 'string' || data['userid'] instanceof String)) {
            throw new Error("Expected the field `userid` to be a primitive type in the JSON string but got " + data['userid']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['thumb'] && !(typeof data['thumb'] === 'string' || data['thumb'] instanceof String)) {
            throw new Error("Expected the field `thumb` to be a primitive type in the JSON string but got " + data['thumb']);
        }
        // ensure the json data is a string
        if (data['area'] && !(typeof data['area'] === 'string' || data['area'] instanceof String)) {
            throw new Error("Expected the field `area` to be a primitive type in the JSON string but got " + data['area']);
        }
        // ensure the json data is a string
        if (data['areaid'] && !(typeof data['areaid'] === 'string' || data['areaid'] instanceof String)) {
            throw new Error("Expected the field `areaid` to be a primitive type in the JSON string but got " + data['areaid']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['categoryid'] && !(typeof data['categoryid'] === 'string' || data['categoryid'] instanceof String)) {
            throw new Error("Expected the field `categoryid` to be a primitive type in the JSON string but got " + data['categoryid']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
RecipePreview.prototype['id'] = undefined;

/**
 * @member {String} userid
 */
RecipePreview.prototype['userid'] = undefined;

/**
 * @member {String} title
 */
RecipePreview.prototype['title'] = undefined;

/**
 * @member {String} thumb
 */
RecipePreview.prototype['thumb'] = undefined;

/**
 * @member {String} area
 */
RecipePreview.prototype['area'] = undefined;

/**
 * @member {String} areaid
 */
RecipePreview.prototype['areaid'] = undefined;

/**
 * @member {String} category
 */
RecipePreview.prototype['category'] = undefined;

/**
 * @member {String} categoryid
 */
RecipePreview.prototype['categoryid'] = undefined;

/**
 * @member {String} description
 */
RecipePreview.prototype['description'] = undefined;






export default RecipePreview;

