/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiAuthCurrentGet200Response from '../model/ApiAuthCurrentGet200Response';
import ApiAuthLoginPost200Response from '../model/ApiAuthLoginPost200Response';
import ApiAuthLoginPostRequest from '../model/ApiAuthLoginPostRequest';
import ApiAuthRegisterPost201Response from '../model/ApiAuthRegisterPost201Response';
import ApiAuthRegisterPostRequest from '../model/ApiAuthRegisterPostRequest';

/**
* Auth service.
* @module api/AuthApi
* @version 1.0.0
*/
export default class AuthApi {

    /**
    * Constructs a new AuthApi. 
    * @alias module:api/AuthApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get current authenticated user and refresh token
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiAuthCurrentGet200Response} and HTTP response
     */
    apiAuthCurrentGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ApiAuthCurrentGet200Response;
      return this.apiClient.callApi(
        '/api/auth/current', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get current authenticated user and refresh token
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiAuthCurrentGet200Response}
     */
    apiAuthCurrentGet() {
      return this.apiAuthCurrentGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Login user
     * @param {module:model/ApiAuthLoginPostRequest} apiAuthLoginPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiAuthLoginPost200Response} and HTTP response
     */
    apiAuthLoginPostWithHttpInfo(apiAuthLoginPostRequest) {
      let postBody = apiAuthLoginPostRequest;
      // verify the required parameter 'apiAuthLoginPostRequest' is set
      if (apiAuthLoginPostRequest === undefined || apiAuthLoginPostRequest === null) {
        throw new Error("Missing the required parameter 'apiAuthLoginPostRequest' when calling apiAuthLoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiAuthLoginPost200Response;
      return this.apiClient.callApi(
        '/api/auth/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Login user
     * @param {module:model/ApiAuthLoginPostRequest} apiAuthLoginPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiAuthLoginPost200Response}
     */
    apiAuthLoginPost(apiAuthLoginPostRequest) {
      return this.apiAuthLoginPostWithHttpInfo(apiAuthLoginPostRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Logout current user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    apiAuthLogoutPostWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/auth/logout', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Logout current user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    apiAuthLogoutPost() {
      return this.apiAuthLogoutPostWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Register a new user
     * @param {module:model/ApiAuthRegisterPostRequest} apiAuthRegisterPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiAuthRegisterPost201Response} and HTTP response
     */
    apiAuthRegisterPostWithHttpInfo(apiAuthRegisterPostRequest) {
      let postBody = apiAuthRegisterPostRequest;
      // verify the required parameter 'apiAuthRegisterPostRequest' is set
      if (apiAuthRegisterPostRequest === undefined || apiAuthRegisterPostRequest === null) {
        throw new Error("Missing the required parameter 'apiAuthRegisterPostRequest' when calling apiAuthRegisterPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiAuthRegisterPost201Response;
      return this.apiClient.callApi(
        '/api/auth/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Register a new user
     * @param {module:model/ApiAuthRegisterPostRequest} apiAuthRegisterPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiAuthRegisterPost201Response}
     */
    apiAuthRegisterPost(apiAuthRegisterPostRequest) {
      return this.apiAuthRegisterPostWithHttpInfo(apiAuthRegisterPostRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
