/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodiesApi);
  }
}(this, function(expect, FoodiesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FoodiesApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('apiUsersFollowingGet', function() {
      it('should call apiUsersFollowingGet successfully', function(done) {
        //uncomment below and update the code to test apiUsersFollowingGet
        //instance.apiUsersFollowingGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersMeGet', function() {
      it('should call apiUsersMeGet successfully', function(done) {
        //uncomment below and update the code to test apiUsersMeGet
        //instance.apiUsersMeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersUserIdFollowersDelete', function() {
      it('should call apiUsersUserIdFollowersDelete successfully', function(done) {
        //uncomment below and update the code to test apiUsersUserIdFollowersDelete
        //instance.apiUsersUserIdFollowersDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersUserIdFollowersGet', function() {
      it('should call apiUsersUserIdFollowersGet successfully', function(done) {
        //uncomment below and update the code to test apiUsersUserIdFollowersGet
        //instance.apiUsersUserIdFollowersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUsersUserIdFollowersPost', function() {
      it('should call apiUsersUserIdFollowersPost successfully', function(done) {
        //uncomment below and update the code to test apiUsersUserIdFollowersPost
        //instance.apiUsersUserIdFollowersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
