/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiAreasGet200ResponseInner from './model/ApiAreasGet200ResponseInner';
import ApiAuthCurrentGet200Response from './model/ApiAuthCurrentGet200Response';
import ApiAuthLoginPost200Response from './model/ApiAuthLoginPost200Response';
import ApiAuthLoginPost200ResponseUser from './model/ApiAuthLoginPost200ResponseUser';
import ApiAuthLoginPostRequest from './model/ApiAuthLoginPostRequest';
import ApiAuthRegisterPost201Response from './model/ApiAuthRegisterPost201Response';
import ApiAuthRegisterPostRequest from './model/ApiAuthRegisterPostRequest';
import ApiRecipesGet200Response from './model/ApiRecipesGet200Response';
import ApiUsersMeGet200Response from './model/ApiUsersMeGet200Response';
import ApiUsersUserIdFollowersGet200ResponseInner from './model/ApiUsersUserIdFollowersGet200ResponseInner';
import AreasApi from './api/AreasApi';
import AuthApi from './api/AuthApi';
import RecipesApi from './api/RecipesApi';
import TestimonialsApi from './api/TestimonialsApi';
import UsersApi from './api/UsersApi';


/**
* API documentation for Foodies project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FoodiesApi = require('index'); // See note below*.
* var xxxSvc = new FoodiesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FoodiesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FoodiesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FoodiesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiAreasGet200ResponseInner model constructor.
     * @property {module:model/ApiAreasGet200ResponseInner}
     */
    ApiAreasGet200ResponseInner,

    /**
     * The ApiAuthCurrentGet200Response model constructor.
     * @property {module:model/ApiAuthCurrentGet200Response}
     */
    ApiAuthCurrentGet200Response,

    /**
     * The ApiAuthLoginPost200Response model constructor.
     * @property {module:model/ApiAuthLoginPost200Response}
     */
    ApiAuthLoginPost200Response,

    /**
     * The ApiAuthLoginPost200ResponseUser model constructor.
     * @property {module:model/ApiAuthLoginPost200ResponseUser}
     */
    ApiAuthLoginPost200ResponseUser,

    /**
     * The ApiAuthLoginPostRequest model constructor.
     * @property {module:model/ApiAuthLoginPostRequest}
     */
    ApiAuthLoginPostRequest,

    /**
     * The ApiAuthRegisterPost201Response model constructor.
     * @property {module:model/ApiAuthRegisterPost201Response}
     */
    ApiAuthRegisterPost201Response,

    /**
     * The ApiAuthRegisterPostRequest model constructor.
     * @property {module:model/ApiAuthRegisterPostRequest}
     */
    ApiAuthRegisterPostRequest,

    /**
     * The ApiRecipesGet200Response model constructor.
     * @property {module:model/ApiRecipesGet200Response}
     */
    ApiRecipesGet200Response,

    /**
     * The ApiUsersMeGet200Response model constructor.
     * @property {module:model/ApiUsersMeGet200Response}
     */
    ApiUsersMeGet200Response,

    /**
     * The ApiUsersUserIdFollowersGet200ResponseInner model constructor.
     * @property {module:model/ApiUsersUserIdFollowersGet200ResponseInner}
     */
    ApiUsersUserIdFollowersGet200ResponseInner,

    /**
    * The AreasApi service constructor.
    * @property {module:api/AreasApi}
    */
    AreasApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The RecipesApi service constructor.
    * @property {module:api/RecipesApi}
    */
    RecipesApi,

    /**
    * The TestimonialsApi service constructor.
    * @property {module:api/TestimonialsApi}
    */
    TestimonialsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
