/**
 * Foodies API
 * API documentation for Foodies project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiAreasGet200ResponseInner from './model/ApiAreasGet200ResponseInner';
import ApiAuthCurrentGet200Response from './model/ApiAuthCurrentGet200Response';
import ApiAuthLoginPost200Response from './model/ApiAuthLoginPost200Response';
import ApiAuthLoginPost200ResponseUser from './model/ApiAuthLoginPost200ResponseUser';
import ApiAuthLoginPostRequest from './model/ApiAuthLoginPostRequest';
import ApiAuthRegisterPost201Response from './model/ApiAuthRegisterPost201Response';
import ApiAuthRegisterPostRequest from './model/ApiAuthRegisterPostRequest';
import ApiCategoriesGet200ResponseInner from './model/ApiCategoriesGet200ResponseInner';
import ApiIngredientsGet200Response from './model/ApiIngredientsGet200Response';
import ApiIngredientsGet200ResponseResultsInner from './model/ApiIngredientsGet200ResponseResultsInner';
import ApiRecipesFavoritesGet200Response from './model/ApiRecipesFavoritesGet200Response';
import ApiRecipesFavoritesGet200ResponseResultsInner from './model/ApiRecipesFavoritesGet200ResponseResultsInner';
import ApiRecipesGet200Response from './model/ApiRecipesGet200Response';
import ApiRecipesGet200ResponseResultsInner from './model/ApiRecipesGet200ResponseResultsInner';
import ApiRecipesGet200ResponseResultsInnerArea from './model/ApiRecipesGet200ResponseResultsInnerArea';
import ApiRecipesGet200ResponseResultsInnerCategory from './model/ApiRecipesGet200ResponseResultsInnerCategory';
import ApiRecipesGet200ResponseResultsInnerCreator from './model/ApiRecipesGet200ResponseResultsInnerCreator';
import ApiRecipesIdFavoriteDelete200Response from './model/ApiRecipesIdFavoriteDelete200Response';
import ApiRecipesIdFavoritePost201Response from './model/ApiRecipesIdFavoritePost201Response';
import ApiRecipesIdGet200Response from './model/ApiRecipesIdGet200Response';
import ApiRecipesIdGet200ResponseArea from './model/ApiRecipesIdGet200ResponseArea';
import ApiRecipesIdGet200ResponseCategory from './model/ApiRecipesIdGet200ResponseCategory';
import ApiRecipesIdGet200ResponseRecipeIngredientsInner from './model/ApiRecipesIdGet200ResponseRecipeIngredientsInner';
import ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient from './model/ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient';
import ApiRecipesIdGet404Response from './model/ApiRecipesIdGet404Response';
import ApiRecipesPopularGet200ResponseInner from './model/ApiRecipesPopularGet200ResponseInner';
import ApiRecipesPopularGet200ResponseInnerCreator from './model/ApiRecipesPopularGet200ResponseInnerCreator';
import ApiRecipesPost201Response from './model/ApiRecipesPost201Response';
import ApiRecipesPost201ResponseArea from './model/ApiRecipesPost201ResponseArea';
import ApiRecipesPost201ResponseCategory from './model/ApiRecipesPost201ResponseCategory';
import ApiRecipesPost201ResponseCreator from './model/ApiRecipesPost201ResponseCreator';
import ApiRecipesPost201ResponseRecipeIngredientsInner from './model/ApiRecipesPost201ResponseRecipeIngredientsInner';
import ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient from './model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient';
import ApiRecipesPostRequestTime from './model/ApiRecipesPostRequestTime';
import ApiTestimonialsGet200ResponseInner from './model/ApiTestimonialsGet200ResponseInner';
import ApiTestimonialsGet200ResponseInnerUser from './model/ApiTestimonialsGet200ResponseInnerUser';
import ApiUsersFollowingGet200ResponseInner from './model/ApiUsersFollowingGet200ResponseInner';
import ApiUsersFollowingGet200ResponseInnerUserFollow from './model/ApiUsersFollowingGet200ResponseInnerUserFollow';
import ApiUsersMeGet200Response from './model/ApiUsersMeGet200Response';
import ApiUsersRecipesGet200Response from './model/ApiUsersRecipesGet200Response';
import ApiUsersUserIdFollowersGet200ResponseInner from './model/ApiUsersUserIdFollowersGet200ResponseInner';
import ApiUsersUserIdFollowersGet200ResponseInnerUserFollow from './model/ApiUsersUserIdFollowersGet200ResponseInnerUserFollow';
import ApiUsersUserIdGet200Response from './model/ApiUsersUserIdGet200Response';
import ApiUsersUserIdRecipesGet200Response from './model/ApiUsersUserIdRecipesGet200Response';
import ApiUsersUserIdRecipesGet200ResponseResultsInner from './model/ApiUsersUserIdRecipesGet200ResponseResultsInner';
import Ingredient from './model/Ingredient';
import PopularRecipe from './model/PopularRecipe';
import Recipe from './model/Recipe';
import RecipeArea from './model/RecipeArea';
import RecipeCategory from './model/RecipeCategory';
import RecipeCreator from './model/RecipeCreator';
import RecipeIngredientItem from './model/RecipeIngredientItem';
import RecipePreview from './model/RecipePreview';
import RecipePreviewArea from './model/RecipePreviewArea';
import RecipesListResponse from './model/RecipesListResponse';
import AreasApi from './api/AreasApi';
import AuthApi from './api/AuthApi';
import CategoriesApi from './api/CategoriesApi';
import IngredientsApi from './api/IngredientsApi';
import RecipesApi from './api/RecipesApi';
import TestimonialsApi from './api/TestimonialsApi';
import UsersApi from './api/UsersApi';


/**
* API documentation for Foodies project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FoodiesApi = require('index'); // See note below*.
* var xxxSvc = new FoodiesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FoodiesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FoodiesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FoodiesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiAreasGet200ResponseInner model constructor.
     * @property {module:model/ApiAreasGet200ResponseInner}
     */
    ApiAreasGet200ResponseInner,

    /**
     * The ApiAuthCurrentGet200Response model constructor.
     * @property {module:model/ApiAuthCurrentGet200Response}
     */
    ApiAuthCurrentGet200Response,

    /**
     * The ApiAuthLoginPost200Response model constructor.
     * @property {module:model/ApiAuthLoginPost200Response}
     */
    ApiAuthLoginPost200Response,

    /**
     * The ApiAuthLoginPost200ResponseUser model constructor.
     * @property {module:model/ApiAuthLoginPost200ResponseUser}
     */
    ApiAuthLoginPost200ResponseUser,

    /**
     * The ApiAuthLoginPostRequest model constructor.
     * @property {module:model/ApiAuthLoginPostRequest}
     */
    ApiAuthLoginPostRequest,

    /**
     * The ApiAuthRegisterPost201Response model constructor.
     * @property {module:model/ApiAuthRegisterPost201Response}
     */
    ApiAuthRegisterPost201Response,

    /**
     * The ApiAuthRegisterPostRequest model constructor.
     * @property {module:model/ApiAuthRegisterPostRequest}
     */
    ApiAuthRegisterPostRequest,

    /**
     * The ApiCategoriesGet200ResponseInner model constructor.
     * @property {module:model/ApiCategoriesGet200ResponseInner}
     */
    ApiCategoriesGet200ResponseInner,

    /**
     * The ApiIngredientsGet200Response model constructor.
     * @property {module:model/ApiIngredientsGet200Response}
     */
    ApiIngredientsGet200Response,

    /**
     * The ApiIngredientsGet200ResponseResultsInner model constructor.
     * @property {module:model/ApiIngredientsGet200ResponseResultsInner}
     */
    ApiIngredientsGet200ResponseResultsInner,

    /**
     * The ApiRecipesFavoritesGet200Response model constructor.
     * @property {module:model/ApiRecipesFavoritesGet200Response}
     */
    ApiRecipesFavoritesGet200Response,

    /**
     * The ApiRecipesFavoritesGet200ResponseResultsInner model constructor.
     * @property {module:model/ApiRecipesFavoritesGet200ResponseResultsInner}
     */
    ApiRecipesFavoritesGet200ResponseResultsInner,

    /**
     * The ApiRecipesGet200Response model constructor.
     * @property {module:model/ApiRecipesGet200Response}
     */
    ApiRecipesGet200Response,

    /**
     * The ApiRecipesGet200ResponseResultsInner model constructor.
     * @property {module:model/ApiRecipesGet200ResponseResultsInner}
     */
    ApiRecipesGet200ResponseResultsInner,

    /**
     * The ApiRecipesGet200ResponseResultsInnerArea model constructor.
     * @property {module:model/ApiRecipesGet200ResponseResultsInnerArea}
     */
    ApiRecipesGet200ResponseResultsInnerArea,

    /**
     * The ApiRecipesGet200ResponseResultsInnerCategory model constructor.
     * @property {module:model/ApiRecipesGet200ResponseResultsInnerCategory}
     */
    ApiRecipesGet200ResponseResultsInnerCategory,

    /**
     * The ApiRecipesGet200ResponseResultsInnerCreator model constructor.
     * @property {module:model/ApiRecipesGet200ResponseResultsInnerCreator}
     */
    ApiRecipesGet200ResponseResultsInnerCreator,

    /**
     * The ApiRecipesIdFavoriteDelete200Response model constructor.
     * @property {module:model/ApiRecipesIdFavoriteDelete200Response}
     */
    ApiRecipesIdFavoriteDelete200Response,

    /**
     * The ApiRecipesIdFavoritePost201Response model constructor.
     * @property {module:model/ApiRecipesIdFavoritePost201Response}
     */
    ApiRecipesIdFavoritePost201Response,

    /**
     * The ApiRecipesIdGet200Response model constructor.
     * @property {module:model/ApiRecipesIdGet200Response}
     */
    ApiRecipesIdGet200Response,

    /**
     * The ApiRecipesIdGet200ResponseArea model constructor.
     * @property {module:model/ApiRecipesIdGet200ResponseArea}
     */
    ApiRecipesIdGet200ResponseArea,

    /**
     * The ApiRecipesIdGet200ResponseCategory model constructor.
     * @property {module:model/ApiRecipesIdGet200ResponseCategory}
     */
    ApiRecipesIdGet200ResponseCategory,

    /**
     * The ApiRecipesIdGet200ResponseRecipeIngredientsInner model constructor.
     * @property {module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInner}
     */
    ApiRecipesIdGet200ResponseRecipeIngredientsInner,

    /**
     * The ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient model constructor.
     * @property {module:model/ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient}
     */
    ApiRecipesIdGet200ResponseRecipeIngredientsInnerIngredient,

    /**
     * The ApiRecipesIdGet404Response model constructor.
     * @property {module:model/ApiRecipesIdGet404Response}
     */
    ApiRecipesIdGet404Response,

    /**
     * The ApiRecipesPopularGet200ResponseInner model constructor.
     * @property {module:model/ApiRecipesPopularGet200ResponseInner}
     */
    ApiRecipesPopularGet200ResponseInner,

    /**
     * The ApiRecipesPopularGet200ResponseInnerCreator model constructor.
     * @property {module:model/ApiRecipesPopularGet200ResponseInnerCreator}
     */
    ApiRecipesPopularGet200ResponseInnerCreator,

    /**
     * The ApiRecipesPost201Response model constructor.
     * @property {module:model/ApiRecipesPost201Response}
     */
    ApiRecipesPost201Response,

    /**
     * The ApiRecipesPost201ResponseArea model constructor.
     * @property {module:model/ApiRecipesPost201ResponseArea}
     */
    ApiRecipesPost201ResponseArea,

    /**
     * The ApiRecipesPost201ResponseCategory model constructor.
     * @property {module:model/ApiRecipesPost201ResponseCategory}
     */
    ApiRecipesPost201ResponseCategory,

    /**
     * The ApiRecipesPost201ResponseCreator model constructor.
     * @property {module:model/ApiRecipesPost201ResponseCreator}
     */
    ApiRecipesPost201ResponseCreator,

    /**
     * The ApiRecipesPost201ResponseRecipeIngredientsInner model constructor.
     * @property {module:model/ApiRecipesPost201ResponseRecipeIngredientsInner}
     */
    ApiRecipesPost201ResponseRecipeIngredientsInner,

    /**
     * The ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient model constructor.
     * @property {module:model/ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient}
     */
    ApiRecipesPost201ResponseRecipeIngredientsInnerIngredient,

    /**
     * The ApiRecipesPostRequestTime model constructor.
     * @property {module:model/ApiRecipesPostRequestTime}
     */
    ApiRecipesPostRequestTime,

    /**
     * The ApiTestimonialsGet200ResponseInner model constructor.
     * @property {module:model/ApiTestimonialsGet200ResponseInner}
     */
    ApiTestimonialsGet200ResponseInner,

    /**
     * The ApiTestimonialsGet200ResponseInnerUser model constructor.
     * @property {module:model/ApiTestimonialsGet200ResponseInnerUser}
     */
    ApiTestimonialsGet200ResponseInnerUser,

    /**
     * The ApiUsersFollowingGet200ResponseInner model constructor.
     * @property {module:model/ApiUsersFollowingGet200ResponseInner}
     */
    ApiUsersFollowingGet200ResponseInner,

    /**
     * The ApiUsersFollowingGet200ResponseInnerUserFollow model constructor.
     * @property {module:model/ApiUsersFollowingGet200ResponseInnerUserFollow}
     */
    ApiUsersFollowingGet200ResponseInnerUserFollow,

    /**
     * The ApiUsersMeGet200Response model constructor.
     * @property {module:model/ApiUsersMeGet200Response}
     */
    ApiUsersMeGet200Response,

    /**
     * The ApiUsersRecipesGet200Response model constructor.
     * @property {module:model/ApiUsersRecipesGet200Response}
     */
    ApiUsersRecipesGet200Response,

    /**
     * The ApiUsersUserIdFollowersGet200ResponseInner model constructor.
     * @property {module:model/ApiUsersUserIdFollowersGet200ResponseInner}
     */
    ApiUsersUserIdFollowersGet200ResponseInner,

    /**
     * The ApiUsersUserIdFollowersGet200ResponseInnerUserFollow model constructor.
     * @property {module:model/ApiUsersUserIdFollowersGet200ResponseInnerUserFollow}
     */
    ApiUsersUserIdFollowersGet200ResponseInnerUserFollow,

    /**
     * The ApiUsersUserIdGet200Response model constructor.
     * @property {module:model/ApiUsersUserIdGet200Response}
     */
    ApiUsersUserIdGet200Response,

    /**
     * The ApiUsersUserIdRecipesGet200Response model constructor.
     * @property {module:model/ApiUsersUserIdRecipesGet200Response}
     */
    ApiUsersUserIdRecipesGet200Response,

    /**
     * The ApiUsersUserIdRecipesGet200ResponseResultsInner model constructor.
     * @property {module:model/ApiUsersUserIdRecipesGet200ResponseResultsInner}
     */
    ApiUsersUserIdRecipesGet200ResponseResultsInner,

    /**
     * The Ingredient model constructor.
     * @property {module:model/Ingredient}
     */
    Ingredient,

    /**
     * The PopularRecipe model constructor.
     * @property {module:model/PopularRecipe}
     */
    PopularRecipe,

    /**
     * The Recipe model constructor.
     * @property {module:model/Recipe}
     */
    Recipe,

    /**
     * The RecipeArea model constructor.
     * @property {module:model/RecipeArea}
     */
    RecipeArea,

    /**
     * The RecipeCategory model constructor.
     * @property {module:model/RecipeCategory}
     */
    RecipeCategory,

    /**
     * The RecipeCreator model constructor.
     * @property {module:model/RecipeCreator}
     */
    RecipeCreator,

    /**
     * The RecipeIngredientItem model constructor.
     * @property {module:model/RecipeIngredientItem}
     */
    RecipeIngredientItem,

    /**
     * The RecipePreview model constructor.
     * @property {module:model/RecipePreview}
     */
    RecipePreview,

    /**
     * The RecipePreviewArea model constructor.
     * @property {module:model/RecipePreviewArea}
     */
    RecipePreviewArea,

    /**
     * The RecipesListResponse model constructor.
     * @property {module:model/RecipesListResponse}
     */
    RecipesListResponse,

    /**
    * The AreasApi service constructor.
    * @property {module:api/AreasApi}
    */
    AreasApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The CategoriesApi service constructor.
    * @property {module:api/CategoriesApi}
    */
    CategoriesApi,

    /**
    * The IngredientsApi service constructor.
    * @property {module:api/IngredientsApi}
    */
    IngredientsApi,

    /**
    * The RecipesApi service constructor.
    * @property {module:api/RecipesApi}
    */
    RecipesApi,

    /**
    * The TestimonialsApi service constructor.
    * @property {module:api/TestimonialsApi}
    */
    TestimonialsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
